apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "social-media-fastapi.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "1440"
