apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }} 
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }} 
  selector:
    matchLabels:
      app: {{ .Chart.Name }} 
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }} 
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        ports:
        - containerPort: 5000
