apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer | default "letsencrypt" }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"


spec:
  ingressClassName: {{.Values.ingressClassName | default "nginx" }}
  tls:
  - hosts:
    - {{ .Values.domain}}
    secretName: {{ .Values.ingress.tls.secretName | default "portfolio-tls" }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: 5000
