apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  type:
  ports:
    - protocol: TCP
      port: 5000 
      targetPort: 5000
