apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Namespace }}-external-secret"
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  target:
    name: "{{ .Release.Namespace }}-secret"
    creationPolicy: Owner
    deletionPolicy: Delete

  secretStoreRef:
    name: "{{ .Release.Namespace }}-secret-store"
    kind: SecretStore

  data:
    - secretKey: DB_DATABASE
      remoteRef:
        key: "{{ .Release.Namespace }}-pguser-{{ .Release.Namespace }}"
        property: dbname

    - secretKey: DB_HOST
      remoteRef:
        key: "{{ .Release.Namespace }}-pguser-{{ .Release.Namespace }}"
        property: host

    - secretKey: DB_PASSWORD
      remoteRef:
        key: "{{ .Release.Namespace }}-pguser-{{ .Release.Namespace }}"
        property: password

    - secretKey: DB_PORT
      remoteRef:
        key: "{{ .Release.Namespace }}-pguser-{{ .Release.Namespace }}"
        property: port

    - secretKey: DB_USERNAME
      remoteRef:
        key: "{{ .Release.Namespace }}-pguser-{{ .Release.Namespace }}"
        property: user
