image:
  repository: ujstor/working_hours
  pullPolicy: IfNotPresent
  tag: "1.0.1"
replicaCount: 1
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
service:
  type: ClusterIP
  port: 8501
  targetPort: 8501
ingress:
  enabled: true
  className: "nginx"
  annotations: 
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: working-hours.ujstor.com
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: streamlit-wh-tls
     hosts:
       - working-hours.ujstor.com
