image:
  repository: ujstor/working_hours
  pullPolicy: IfNotPresent
  tag: "1.0.1"
replicaCount: 1
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
service:
  type: ClusterIP
  port: 8501
  targetPort: 8501
ingress:
  enabled: true
  className: "nginx"
  annotations: 
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: working-hours.ujstor.com
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: streamlit-wh-tls
     hosts:
       - working-hours.ujstor.com
