image:
  repository: ujstor/flask-notes
  pullPolicy: IfNotPresent
  tag: "1.0.0"
replicaCount: 1
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
service:
  type: ClusterIP
  port: 5010
  targetPort: 5010
ingress:
  enabled: true
  className: "nginx"
  annotations: 
    cert-manager.io/cluster-issuer: "letsencrypt" 
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: notes.ujstor.com
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: notes-flask-tls 
     hosts:
       - notes.ujstor.com
