image:
  repository: ujstor/todo-go-htmx
  pullPolicy: IfNotPresent
  tag: "1.1.1"
replicaCount: 1
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
ingress:
  enabled: true
  className: "nginx"
  annotations: 
    cert-manager.io/cluster-issuer: "letsencrypt" 
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: todo.ujstor.com
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: todo-htmx-tls 
     hosts:
       - todo.ujstor.com

postgres-cluster:
  postgresVersion: 16
  instanceMemory: 500Mi
  instanceCPU: 250m
  instanceReplicas: 1
  instances:
    - name: todo-htmx-go
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 500Mi
  port: 5432
  # Add minimal backup configuration
  pgBackRestConfig:
    repos:
      - name: nobackup1
        volume:
          volumeClaimSpec:
            accessModes:
              - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Mi
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
