image:
  repository: harbor.k3s0.ujstor.com/docker/github-readme-stats
  pullPolicy: IfNotPresent
  tag: "latest"
  pullSecret: regcred
replicaCount: 1
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 252Mi
service:
  type: ClusterIP
  port: 9000
  targetPort: 9000
ingress:
  enabled: true
  className: "nginx"
  annotations: 
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: readme-stats.ujstor.com
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: github-readme-stats-tls
     hosts:
       - readme-stats.ujstor.com
