apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-django.fullname" . }}-config-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SECRET_KEY: "{{ randAlphaNum 64 | b64enc }}"
